name: The Common Ground Sophisticate Media Kit
favicon: null
layout_spectrum: 0.8657764110248536
typography_spectrum: 0.34648980130441487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.49462810321711004
  lightness: 0.1717945102136582
  saturation: 0.13685377733781934
  rhythmicContrast: 0.5402175125200301
purpose: []
